default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: wiki
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: xiguashe_development

production:
  <<: *default
  database: xiguashe_production